### ISSUE TITLE
Crash when cannot grab keyboard fast enough

### ISSUE THREAD

**Issue by bombela** [DaveDavenport/rofi#526]
## Version
Version: 1.2.0

## Configuration

https://gist.github.com/bombela/d33e48c09118c50fe8e0ab6288b1761f

## Launch Command

The commandline used to launch **rofi**
```
rofi -show run 2>>/tmp/rofi.err
```
## Steps to reproduce

Add a shortcut in i3 window manager, like:
```
bindsym $mod+d exec rofi -show run 2>>/tmp/rofi.err
```

## What behaviour you see

As long as I keep the i3 shorcut pressed, rofi `abort()` before showing the rofi window. As soon as I release the i3 shortcut, rofi shows up.

Using my example, I find in /tmp/rofi.err something like:
```
[...]
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to grab keyboard, even after 500000 uS.**
ERROR:source/view.c:264:rofi_view_set_active: assertion failed: (( current_active_menu == NULL && state != NULL ) || ( current_active_menu != NULL && state == NULL ))
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
[...]
```
I suspect it must be the keyboard resource being held by i3?

## What behaviour you expect to see

Rofi should start and display itself, keeping the i3 shortcut down would do nothing as i3 is waiting for rofi to exit.

**Comment by DaveDavenport** [comment]
This crash has been fixed ages ago.

**Comment by bombela** [comment]
I tried again with a fresh build from master: Version: 1.3.1-184-g0e1b02d-dirty (master)
Full commit ID: 0e1b02d2f42bed92f2c4e9a95e1ac80419a34606

And the problem remains, with the same errors.

**Comment by DaveDavenport** [comment]
The crash or the errors?

**Comment by DaveDavenport** [comment]
The errors are to be expected.
1.) If you hold they key, I3 will keep re-launching rofi, that is explaining this error:
```
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
```

There are two "solutions" (as mentioned in other bug report),  Make i3 launch rofi on key-release (see rofi manpage or i3 documentation), or add the -lazy-grab option this will not solve the issue, but show the window before it can grab the keyboard.

**Comment by bombela** [comment]
That's the stderr from rofi using the same i3 binding:
`bindsym $mod+d exec rofi -show run 2>>/tmp/rofi.err)`

```
$ cat /tmp/rofi.err 
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to grab keyboard, even after 500000 uS.Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
Failed to set lock on pidfile: Rofi already running?
Got error: -1 Resource temporarily unavailable
```

So rofi exits quickly after printing an error (and I believe it exits via a call to `abort()`).

**Comment by DaveDavenport** [comment]
Believe or checked?

**Comment by bombela** [comment]
Believe. Not checked. Note there is no assertion error anymore it *seems*. (I keep the shortcut pressed until it fills up 100s lines of errors).

I will turn on auditing, give me few minutes.

**Comment by DaveDavenport** [comment]
Anyway, this is fully to be expected behavior.. I3 keeps relaunching rofi if you hold they keys (key-repeat times a second) and rofi cannot grab keyboard until it is been released by i3. 

See my reply above.

**Comment by bombela** [comment]
The result of the kernel audit:

```
type=SYSCALL msg=audit(1484339633.431:37004): arch=c000003e syscall=59 success=yes exit=0 a0=55a072c7dc30 a1=55a072977be8 a2=55a072c7dab8 a3=1 items=2 ppid=8449 pid=8450 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="rofi" exe="/home/bombela/bin/rofi" key=(null)
type=EXECVE msg=audit(1484339633.431:37004): argc=3 a0="rofi" a1="-show" a2="run"
type=CWD msg=audit(1484339633.431:37004): cwd="/home/bombela"
type=PATH msg=audit(1484339633.431:37004): item=0 name="/home/bombela/bin/rofi" inode=29361453 dev=fd:01 mode=0100775 ouid=1000 ogid=1000 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1484339633.431:37004): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=8390834 dev=fd:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=PROCTITLE msg=audit(1484339633.431:37004): proctitle=726F6669002D73686F770072756E
```
So it exits with 0. 

Now I understand why you said the problem was fixed, you were talking about the crash, and I was talking about the behavior of i3 vs rofi grabbing the keyboard!

Effectively `-lazy-grab` wont prevent starting extra rofi instances if you keep pressing the shortcut, but it makes for a nicer user experience as the window pops right away. In fact, I have tested few times, and I seem to react faster than the time it takes to i3 to start another instance of rofi anyway, which makes everything feel really snappy for me!

Thanks for your instantaneous reply and time. And of course thanks for making rofi!

**Comment by DaveDavenport** [comment]
I don't see anything else I can do except having a pid file to stop multiple instances.
I am unsure why i3 does this crazy relaunch and does not try to stop this.
